# Hannah Garrett
# Numpy Assignment 2
# DS 160

#### Part 1

In [1]:
import numpy as np
array=([[10,20],[30,40]])
array

[[10, 20], [30, 40]]

In [2]:
np.square(array)

array([[ 100,  400],
       [ 900, 1600]])

In [3]:
np.add(array, 100)

array([[110, 120],
       [130, 140]])

In [4]:
np.multiply(array, 5)

array([[ 50, 100],
       [150, 200]])

In [5]:
np.sqrt(array)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

#### Part 2

In [6]:
array1=np.arange(3,30,3)
array1.resize(3,3)
array1

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [7]:
array2=np.linspace(10,20,9)
array2.resize(3,3)
array2

array([[10.  , 11.25, 12.5 ],
       [13.75, 15.  , 16.25],
       [17.5 , 18.75, 20.  ]])

In [8]:
array3=array1*array2
array3

array([[ 30. ,  67.5, 112.5],
       [165. , 225. , 292.5],
       [367.5, 450. , 540. ]])

#### Part 3

In [9]:
p1=np.load("process1.npy")
p1

array([[52, 12, 81,  0, 58]], dtype=int32)

In [10]:
p2=np.load("process2.npy")
p2

array([[96,  4, 61, 16, 43]], dtype=int32)

In [11]:
p3=np.load("process3.npy")
p3

array([[38, 96, 45, 17, 58]], dtype=int32)

In [12]:
p4=np.load("process4.npy")
p4

array([[97, 21, 22, 25,  6]], dtype=int32)

In [13]:
p5=np.load("process5.npy")
p5

array([[77,  6, 19,  2, 74]], dtype=int32)

In [14]:
process=np.vstack([p1,p2,p3,p4,p5])
process

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]], dtype=int32)

In [15]:
np.mean(process, axis=0)

array([72. , 27.8, 45.6, 12. , 47.8])